CELERY_BROKER_URL = 'redis url'
CELERY_ACCCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_HOST_USER = 'email'
EMAIL_HOST_PASSWORD = '******'
EMAIL_PORT = 587
EMAIL_USE_TLS = True